### ISSUE TITLE
Looks like MPM is now using frequency domain acf?

### ISSUE THREAD

**Issue by adamski** [sevagh/pitch-detection#11]
First of all - thanks for your implementation! I borrowed some of your code a while ago here: https://github.com/adamski/PitchDetector

MPM is definitely the best algorithm I've found for musical sounds, after a lot of tests. 
My only issue has been speed on slow devices e.g. older phones, it is much slower than FFT based detection methods. I've just come back to check this repository and it looks like you're now using FFT for the autocorrelation rather than the time-based method. Is this correct? If so, could I suggest to update the Readme?

**Comment by sevagh** [comment]
You're right, I now rely on any type of cross-correlation: https://github.com/sevagh/pitch-detection/blob/master/pitch/mpm.hpp#L31

I'll update the README.

**Comment by sevagh** [comment]
FYI when I have the time I'll be messing around with: http://www.fftw.org/pruned.html

This has the potential to make autocorrelation really fast.
