### ISSUE TITLE
xcorr.h missing

### ISSUE THREAD

**Issue by bohboh10** [sevagh/pitch-detection#17]
Hello,

I think you forgot to push the xcorr.h and relative files into the repo. On file autocorrelation.cpp line 8:

extern "C" {
#include <xcorr.h>
}

**Comment by sevagh** [comment]
Actually this is based on another of my projects: https://github.com/sevagh/libxcorr

I expect that to be installed when using `pitch-detection`. Should be simply to install: https://github.com/sevagh/libxcorr#buildinstall

**Comment by bohboh10** [comment]
Thanks for the answer. I'm now tried to install the xcorr library but I got an error. I wrote you on the xcorr repo.

**Comment by bohboh10** [comment]
Thanks almost... now running the example:
sinewave.cpp:29:2: warning: 'auto' type specifier is a C++11 extension
      [-Wc++11-extensions]
        auto x = generate_sinewave(FLAGS_size, FLAGS_freq, 48000);
        ^
sinewave.cpp:49:22: error: expected ';' at end of declaration
        std::vector<int> lut {};
                            ^
                            ;
sinewave.cpp:50:41: error: expected ';' at end of declaration
        std::vector<double> tone_single_channel {};
                                               ^
                                               ;
1 warning and 2 errors generated.

**Comment by sevagh** [comment]
I'll download `clang` and check it out.

**Comment by sevagh** [comment]
You're on OSX? Does clang not support `C++11+`? I required `C++17` in the Makefile, for which this is valid syntax.

Also this is worrying:

```
sinewave.cpp:29:2: warning: 'auto' type specifier is a C++11 extension
[-Wc++11-extensions]```

**Comment by sevagh** [comment]
BTW, I'm resolving this by absorbing `xcorr` back into this project. I'm going to abandon my [libxcorr](https://github.com/sevagh/libxcorr) repository.

**Comment by sevagh** [comment]
https://github.com/sevagh/pitch-detection/blob/master/src/xcorr.hpp
