### ISSUE TITLE
Portable version of MPM

### ISSUE THREAD

**Issue by doffen** [sevagh/pitch-detection#32]
Could you make a portable version of MPM that is pure C/C++ without linking to an FFT library?  Maybe using KissFFT (https://sourceforge.net/projects/kissfft/files/kissfft/v1_3_0), or using time-domain based autocorrelation instead of FFT (not sure which approach would execute the autocorrelation faster)?

**Comment by sevagh** [comment]
https://github.com/sevagh/pitch-detection/blob/master/src/mpm.cpp#L55

Time-domain autocorrelation is slower than using KissFFT but it's the easiest solution for now. I don't have the desire to play with Yet Another FFT Library.
