### ISSUE TITLE
Use of "sign" in FFTS used by MPM

### ISSUE THREAD

**Issue by doffen** [sevagh/pitch-detection#34]
According to comments in ffts.h, the second "sign" argument to ffts_init_1d() should be -1 for forward (real to complex) and +1 for backward (complex to real), however the value in mpm.c is equal to 0:
	auto fft_forward = ffts_init_1d(N2, false);
	auto fft_backward = ffts_init_1d(N2, false);
How can this work correctly with a value of false=0?  Is it documented somewhere how this is supposed to work?

**Comment by sevagh** [comment]
I got the same results as you - if I changed my code (which doesn't feel like it makes sense), the output wasn't too good  ¯\_(ツ)_/¯

I could look into it further some day.

**Comment by sevagh** [comment]
With the new MPM changes, this is no longer an issue: https://github.com/sevagh/pitch-detection/issues/35
