### ISSUE TITLE
much faster mpm auto-correlation

### ISSUE THREAD

**Issue by doffen** [sevagh/pitch-detection#35]
Today I met with a friend, Ron Schafer, co-author of the textbook "Discrete-Time Signal Processing" to get a better understanding of how the mpm auto-correlation works.  While reviewing the code he figured out that it is possible to completely eliminate one of the three FFTs in acorr_r() and still get identical results in a much shorter time!  Here's the new code, which I have validated.  I suggest you try it and if you agree, replace your existing acorr_r code with this improvement.
    int N = signal.size();
    int N2 = 2 * N;

    auto fft_forward = ffts_init_1d(N2, FFTS_FORWARD);
    auto fft_backward = ffts_init_1d(N2, FFTS_BACKWARD);

    std::vector<std::complex<float>> signalb_ext(N2);

    for (int i = 0; i < N; i++)
        signalb_ext[i] = {float(signal[i]), 0.0};

    std::vector<std::complex<float>> outb(N2);
    std::vector<std::complex<float>> out(N2);
    std::vector<std::complex<float>> result(N2);

    ffts_execute(fft_forward, signalb_ext.data(), outb.data());

    std::complex<float> scale = {1.0f / (float)N2, 0.0};
    for (int i = 0; i < N; ++i) 
         out[i] = outb[i] * std::conj(outb[i]) * scale;

    ffts_execute(fft_backward, out.data(), result.data());

    ffts_free(fft_forward);
    ffts_free(fft_backward);

    std::vector<double> normalized_result(N, 0.0);
    for (int i = 0; i < N; ++i) 
         normalized_result[i] = std::real(result[i]) / std::real(result[0]);
    return normalized_result;

**Comment by sevagh** [comment]
My results agree with this so I'll push it. Thanks.

I took my undergrad DSP courses with his textbook, and now several years later he indirectly contributed to my GitHub code - what a cool world.

**Comment by sevagh** [comment]
https://github.com/sevagh/pitch-detection/commit/1d3b0b4d4db8f517d294a976d7e0b1cfea0c9699
