### ISSUE TITLE
MpmSinewaveTest fails for 77.0

### ISSUE THREAD

**Issue by j605** [sevagh/pitch-detection#50]
```
[----------] 7 tests from MpmSinewave/MpmSinewaveTest
[ RUN      ] MpmSinewave/MpmSinewaveTest.GetFreq/0
test/sinewave_test.cpp:18: Failure
The difference between freq and pitch is 78, which exceeds 0.01 * freq, where
freq evaluates to 77,
pitch evaluates to -1, and
0.01 * freq evaluates to 0.77000000000000002.
```

**Comment by sevagh** [comment]
This is kind of on purpose - it proves that YIN can handle lower pitches.

https://github.com/sevagh/pitch-detection/blob/master/include/pitch_detection_priv.h#L7

https://github.com/sevagh/pitch-detection/blob/cc2e6678b80839ff2382baec007a28cb6b0d6b2d/src/mpm.cpp#L79

Looking at the code now it seems that I just discard lower values for no reason - I don't see any mentions in the paper that low pitches are invalid...

**Comment by sevagh** [comment]
I disabled the 77.0Hz test for the MPM, and put a note in the test comment: https://github.com/sevagh/pitch-detection/blob/master/test/sinewave_test.cpp#L82

Now the test suite succeeds on every run.
