### ISSUE TITLE
Using autocorrelation instead of calculating NSDF in MPM

### ISSUE THREAD

**Issue by VadymBezdushnyi** [sevagh/pitch-detection#85]
Can you please explain, why in https://github.com/sevagh/pitch-detection/blob/34b198b661839a5c2dc007103128b6a1725e469d/src/mpm.cpp#L128 you pass result from autocorrelation to the function which(according to paper) should take NSDF?

**Comment by sevagh** [comment]
Sure. Difference function and autocorrelation are quite similar.

In MPM, normalized square difference and autocorrelation functions are basically the same thing. I found in some exploration (https://github.com/sevagh/pitch-detection/tree/master/misc/mcleod#51---peak-picking-with-parabolic-interpolation---putting-it-all-together) that once you add the rest of the algorithm, autocorrelation and NSDF perform the same.

As a plus, I can use the same autocorrelation function in YIN (https://github.com/sevagh/pitch-detection/blob/34b198b661839a5c2dc007103128b6a1725e469d/src/yin.cpp#L91-L102), except there, it's a different variant of autocorrelation - the cumulative mean normalized difference function/CMNDF. It needs some post-processing on the autocorrelation function, unlike MPM which can use the autocorrelation as a direct substitute of the NSDF.

**Comment by VadymBezdushnyi** [comment]
Thanks for explaining your approach in MPM.   
Also, one more thing in YIN implementation remains unclear for me.

In the code above you are using:   
```
ya->out_real[0] + ya->out_real[1] - 2 * ya->out_real[tau]; 
```
Why `ya->out_real[1]` is used here?  

In my understanding this algorithm shoud look like:
```
T prefix_sum = 0;
for (int tau = 0; tau < ya->N / 2; tau++) 
{
    ya->yin_buffer[tau] = 2 * ya->out_real[0] - prefix_sum - 2 * ya->out_real[tau];
    prefix_sum += audio_buffer[tau];
}
```
So we add sum of all squares(`ya->out_real[0]`) and sum of all squares which start from `tau`(`ya->out_real[0] - prefix_sum`)

**Comment by sevagh** [comment]
I did that with trial and error.

You can see I used to have different code - similar to yours but missing the prefix_sum (maybe that's why it never worked): https://github.com/sevagh/pitch-detection/commit/521481b346854f4b6b6df9e7066f359db696c0e6#diff-ec0aedadeb2a8475b194edb462daf8fcd235be1a347ae5d49feddbe7ede87559L112

**Comment by sevagh** [comment]
I would take a look at `ya->out_real[1]` (maybe print it). Perhaps by luck it's some approximation of the original algorithm.

**Comment by VadymBezdushnyi** [comment]
Thanks, for clarification. In the end, the best method is one which works :)
